app/blog/urls.py
from . import views
from django.urls import path
from django.views.decorators.cache import cache_page

urlpatterns = [
    path('all/', views.post_list, name='blog_all'),
    path('post/<int:pk>/', views.post_detail, name='blog_detail'),
    path('post/new/', views.post_new, name='blog_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='blog_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='blog_delete'),
    path('comment/success/', views.blog_comment_success, name='blog_comment_success'),
    path('category/', views.category_list, name='category_all'),
    path('category/<int:pk>/', views.category_detail, name='category_detail'),
]

app/library/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all', views.LibraryList.as_view(), name='library_all'),
    path('<slug:slug>/', views.library_detail, name='library_detail'),
    path('new', views.library_new, name='library_new'),
    path('<int:pk>/edit/', views.library_edit, name='library_edit'),
]

app/mentoro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import debug_toolbar

# Sentry SDK
def trigger_error(request):
    division_by_zero = 1 / 0


# Django Debug Toolbar
if bool(settings.DEBUG):
    import debug_toolbar


urlpatterns = [
    # sentry werify
    path('sentry-debug/', trigger_error),  # Sentry SDK
    path('__debug__/', include(debug_toolbar.urls)),  # Django Debug Toolbar https://github.com/jazzband/django-debug-toolbar
    # admin path
    path('admin/', admin.site.urls),
    # defender admin
    path('admin/defender/', include('defender.urls')),
    # Ckeditor uploader
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # sites path
    path('', include('home.urls')),
    # accounts app paths
    path('account/', include('accounts.urls')),
    # dashboard path
    path('dashboard/', include('dashboard.urls')),
    # Mentoro|Courses path
    path('courses/', include('courses.urls')),
    # Mentoro|Mentors path
    path('mentors/', include('mentors.urls')),
    # Mentoro|Library path
    path('library/', include('library.urls')),
    # Mentoro|Blog path
    path('blog/', include('blog.urls')),
]
if bool(settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/library/models.py
from django.db import models
from pyuploadcare.dj.models import ImageField, FileField
from ckeditor.fields import RichTextField

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Category(models.Model):
    title = models.CharField(max_length=150, blank=False, null=False)

    def __str__(self):
        return self.title


class Language(models.Model):
    title = models.CharField(max_length=150, blank=False, null=False)

    def __str__(self):
        return self.title


class Library(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=150, unique=True, blank=False, null=False, verbose_name="Tytuł", help_text='Podaj tytuł wpisu który chcesz dodać')
    slug = models.SlugField(max_length=150, unique=True, default='')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Kategoria", help_text='Wybierz kategorię w której chcesz dodać wpis')
    language = models.ForeignKey(Language, on_delete=models.CASCADE, verbose_name="Język", help_text='Wybierz język w którym są Twoje treści')
    price = models.DecimalField(null=False, blank=False, max_digits=7, decimal_places=2, verbose_name="Cena", help_text="Podaj cenę w złotówkach za która chcesz sprzedawać materiał")
    short_description = RichTextField(blank=False, null=False, max_length=500, verbose_name="Krótki opis", help_text='Dodaj krótki opis. Maksymalna ilość znaków to 500')
    description = RichTextField(blank=False, null=False, verbose_name="Szczegółowy opis", help_text='Podaj szczegółowy opis Twojego materiału.')
    contests = RichTextField(blank=False, null=False, verbose_name="Zawartość i spis treści", help_text='Podaj zawartość i spis treści Twojego materiału')
    requirements = RichTextField(blank=False, null=False, verbose_name="Wymagana wiedza", help_text='Wymagana wiedza do zrozumienia materiału')
    image_preview = ImageField(blank=False, null=False, verbose_name="Zdjęcie podglądowe", help_text='Dodaj zdjęcie podglądowe materiału')
    video_preview = FileField(blank=True, null=True, verbose_name="Wideo prezentacja", help_text='Dodaj film wideo reklamujący i opisujący Twoj materiał')
    file_download = FileField(blank=False, null=False, verbose_name="Plik do pobrania", help_text='Dodaj plik który kupujący będzie mógł pobrać. Dozwolone formaty to: zip, rar, pdf, txt, epub')
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Library, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='comments')
    body = RichTextField(blank=False, null=False, verbose_name="Treść komentarza", help_text='Napisz szczegółowy komentarz. Wesprzyj Twórcę tego postu i przekaż swoje podziękowania lub uwagi.')
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.author)

app/library/forms.py
from django import forms
from .models import Library, Comment

class LibraryForm(forms.ModelForm):

    class Meta:
        model = Library
        fields = ('title', 'category', 'language', 'price', 'short_description', 'description', 'contests', 'requirements', 'image_preview', 'video_preview', 'file_download',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

app/library/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from .models import Library
from .forms import LibraryForm
# Create your views here.

# cache_page(60 * 1) # Cache time to live is 15 minutes.
class LibraryList(generic.ListView):
    queryset = Library.objects.filter(status=1).order_by('-created_date')
    template_name = 'library_all.html'
    paginate_by = 3

#@cache_page(60 * 5) # cache 60s * 5 = 5 minutes
def library_detail(request, slug):
    template_name = 'blog_detail.html'
    post = get_object_or_404(Library, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = LibraryForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            new_comment.name = request.user
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = LibraryForm()

    return render(request, template_name, {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})

#@cache_page(60 * 15) # Cache time to live is 15 minutes.
@login_required
def library_new(request):
    if request.method == "POST":
        form = LibraryForm(request.POST, request.FILES)
        if form.is_valid():
            library_file = form.save(commit=False)
            library_file.author = request.user
            library_file.published_date = timezone.now()
            library_file.save()
            return redirect('library_detail', pk=library_file.pk)
    else:
        form = LibraryForm()
    return render(request, 'library_edit.html', {'form': form})

#@cache_page(60 * 15) # Cache time to live is 1 minutes.
@login_required
def library_edit(request, pk):
    post = get_object_or_404(Library, pk=pk)
    if request.method == "POST":
        form = LibraryForm(request.POST, instance=post)
        if form.is_valid():
            library_file = form.save(commit=False)
            library_file.author = request.user
            library_file.published_date = timezone.now()
            library_file.save()
            return redirect('library_detail', pk=library_file.pk)
    else:
        form = LibraryForm(instance=post)
    return render(request, 'library_edit.html', {'form': form})

app/library/templates/library_all.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="pb-5 bg-theme-milky">
        <div class="container pt-4">
            <form>
                <div class="form-row">
                    <div class="col-7">
                        <input type="text" class="form-control" placeholder="Wpisz czego szukasz">
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <select class="form-control" id="LanguageSelect">
                                <option>Wszystkie języki</option>
                                <option>Angielski</option>
                                <option>Polski</option>
                            </select>
                        </div>
                    </div>
                    <div class="col">
                        <button type="submit" class="btn btn-primary shadow rounded-0 btn-block font-special-bold"><i class="fas fa-search"></i> Szukaj</button>
                    </div>
                </div>
            </form>
            <div class="row">
                <div class="col-lg-3">
                    <div class="pb-3">
                        <a class="btn btn-success btn-block shadow rounded-0" href="{% url 'library_new' %}" role="button"><i class="fas fa-plus"></i> Dodaj pliki</a>
                    </div>
                    <ul class="nav nav-pills flex-column">
                        <li class="nav-item">
                            <a class="nav-link active rounded-0 shadow dark-link" href="{% url 'library_all' %}">Wszystkie kategorie</a>
                        </li>
                        {% for library in library_list %}
                            <li class="nav-item">
                                <a class="nav-link dark-link" href="{% url 'library_all' %}">{{ library.category }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="col-lg-9">
                    {% for library in library_list %}
                        <div class="pb-3">
                            <div class="card rounded-0 shadow">
                                <img src="{{ library.image_preview.url }}" class="img-fluid rounded-0" alt="">
                                <div class="card-body">
                                    <h4 class="float-right text-white font-special-bold bg-theme-gunmetal p-2">${{ library.price }}</h4>
                                    <p class="font-special-bold mb-0">{{ library.language }}</p>
                                    <p>{{ library.category }}</p>
                                    <a href="{% url 'library_detail' library.slug %}" class="h5 text-decoration-none">{{ library.title }}</a>
                                    <p>{{ library.short_description|safe }}</p>
                                    <p class="mb-0">Opublikowane {{ library.created_date }} przez <a href="" class="text-decoration-none">{{ library.author }}</a></p>
                                    <p class="mb-0">Ostatnia aktualizacja {{ library.published_date }}</p>
                                    <p class="mb-0">Pozytywnych <span class="text-success font-special-bold">422</span> i negatywnych <span class="text-danger font-special-bold">13</span> <a href="" class="text-decoration-none">recenzji</a></p>
                                    <p>Sprzedane w ilości <span class="font-special-bold">435</span> sztuk</p>
                                    <div class="row">
                                        <div class="col">
                                            <a href="{% url 'library_detail' library.slug %}" class="btn btn-dark btn-block font-weight-bold shadow rounded-0"><i class="fas fa-info-circle"></i> Sprawdz szczegóły</a>
                                        </div>
                                        <div class="col">
                                            <a href="#" class="btn btn-success btn-block font-weight-bold shadow rounded-0"><i class="fas fa-shopping-cart"></i> Kup teraz</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </section>
{% endblock content %}

app/library/templates/library_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="bg-theme-milky">

    <section class="pt-3">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb rounded-0">
                    <li class="breadcrumb-item"><a href="{% url 'library_all' %}" class="text-decoration-none">Mentoro | Library</a></li>
                    <li class="breadcrumb-item"><a href="#" class="text-decoration-none">{{ library.category }}</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{ library.title }}</li>
                </ol>
            </nav>
        </div>
    </section>

    {% if library.video_preview %}
        <section class="pt-5 pb-5 bg-theme-gunmetal">
            <div class="container">
                <h4 class="text-white text-center">{{ library_file.title }}</h4>
                <p class="text-white text-center pb-3">{{ library_file.description|linebreaksbr }}</p>
                <video id="player" playsinline controls>
                    <source src="{{ library.video_preview.url }}" type='video/mp4'>
                </video>
            </div>
        </section>
    {% endif %}
    <div class="container pt-5 pb-5">
        <div class="row">
            <div class="col-lg-8">
                <div class="card rounded-0 shadow">
                    <img src="{{ library.image_preview.url }}" class="img-fluid" alt="{{ library.title }}">
                    <div class="card-body">
                        <a href="{% url 'library_detail' library.slug %}" class="h5 text-decoration-none">{{ library.title }}</a>
                        <p>Opublikowane {{ library.published_date }}</p>
                        <p class="mb-0 font-special-bold">Krótki opis</p>
                        <p>{{ library.short_description|safe }}</p>
                        <p class="mb-0 font-special-bold">Szczegółowy opis</p>
                        <p>{{ library.description|safe }}</p>
                        <p class="mb-0 font-special-bold">Zawartość i spis treści</p>
                        <p>{{ library.contests|safe }}</p>
                        <p class="mb-0 font-special-bold">Wymagania</p>
                        <p>{{ library.requirements|safe }}</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="card shadow rounded-0">
                    <div class="card-body text-center">
                        <p class="text-muted">Szczegóły</p>
                        <hr class="">
                        <p class="font-special-bold">{{ library.category }}</p>
                        <p class="font-special-bold"><span class="text-success">422</span> / <span class="text-danger">13</span></p>
                        <p>Język <span class="font-special-bold">{{ library.language }}</span></p>
                        <hr>
                        <p><img src="{% static 'img/avatar/adrian.png' %}" class="img-fluid" alt="{{ library.category.author }}"></p>
                        <a href="" class="text-decoration-none">{{ library.author }}</a>
                        <hr>
                        <p>Sprzedane w ilości <span class="font-special-bold">435</span> sztuk</p>
                        <h4 class="text-white font-special-bold bg-theme-gunmetal p-1">{{ library.price }} PLN</h4>
                        <hr>
                        <a class="btn btn-success btn-block shadow rounded-0" href="#" role="button"><i class="fas fa-shopping-cart"></i> Kup teraz</a>
                        <hr>
                        <small>14-Days Money-Back Guarantee</small>
                    </div>
                </div>
                <div class="pt-3"></div>
                <div class="card shadow rounded-0">
                    <div class="card-body text-center">
                        <a class="btn btn-primary shadow rounded-0 btn-block" href="#" role="button">Udostępnij i zarabiaj <i class="fas fa-share-alt"></i></a>
                        <a class="btn btn-primary shadow rounded-0 btn-block" href="#" role="button">Dodaj do listy życzeń <i class="far fa-heart"></i></a>
                        <a class="btn btn-primary shadow rounded-0 btn-block" href="#" role="button">Podaruj <i class="fas fa-gift"></i></a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    </section>
{% endblock content %}

app/library/templates/library_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="pb-5 bg-theme-milky">
        <div class="container pt-4">
            <div class="card shadow rounded-0 border-0">
                <div class="card-body">
                    <form method="post" enctype='multipart/form-data'>
                        {% csrf_token %}
                        {{ form.media }}
                        {% crispy form %}
                        <button type="submit" value="Submit" class="btn btn-success shadow rounded-0 btn-block font-special-bold">Zapisz</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

app/library/templates/library_new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="pb-5 bg-theme-milky">
        <div class="container pt-4">
            <p>new</p>
        </div>
    </section>
{% endblock content %}